# Generated by Django 5.2.5 on 2025-08-23 11:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='design',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='flyer',
            field=models.ImageField(blank=True, null=True, upload_to='event_flyers/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
